name: Build and Deploy
on:
  push:
    branches:
      - main
      - master
jobs:
  build-and-upload:
    runs-on: ubuntu-latest   # could be anything now
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1' # Latest stable Julia release.
    - run: julia -e '
            using Pkg; Pkg.add("Franklin"); using Franklin;
            optimize(prepath="test-fpush",minify=false,prerender=false)'
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: franklin-site
        path: __site

  deploy:
    concurrency: ci-${{ github.ref }}
    needs: [builds-and-upload]
    runs-on: ubuntu-latest # or mac
    permissions:
      contents: write
    steps:
    - name: Git setup
      run: |
        git config user.name "GABot"
        git config user.email "<>"
    - name: Checkout preview
      run: |
        git checkout -B gh-preview
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: franklin-site
        path: __tmp__site
    - name: Copy content
      run: |
        cp -a __tmp__site/. .
    - name: Remove tmp dir
      run: |
        rm -rf __tmp__site
    - name: Push
      run: |
        git commit -am "update" && git push